# Generated by Django 3.2.4 on 2021-06-11 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='static/images/bi.jpg', null=True, upload_to='assets')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('location', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=255)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
