# Generated by Django 3.2.4 on 2021-06-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Permanent', 'Permanent'), ('Contract', 'Contract')], default='Full-time', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1'), ('1-2', '1-2'), ('2-3', '2-3'), ('3-4', '3-4'), ('5-10', '5-10')], default='0-1', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(choices=[('0-100000', '0-100000'), ('100000-200000', '100000-200000'), ('200000-300000', '200000-300000'), ('400000-500000', '400000-500000'), ('500000-1000000', '500000-1000000'), ('Negotiable', 'Negotiable')], default='0-100000', max_length=100),
        ),
    ]
