# Generated by Django 3.2.4 on 2021-06-24 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails', verbose_name='Add thumbnail')),
                ('image', models.ImageField(blank=True, upload_to='images', verbose_name='Add image')),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
